// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeResp.proto

package io.netty.nettyBook2Example.chapter8_Protobuf;

public final class SubscribeRespProto {
  private SubscribeRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscribeRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.SubscribeResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    java.util.List<java.lang.Integer> getSubReqIDList();
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    int getSubReqIDCount();
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    int getSubReqID(int index);

    /**
     * <code>repeated int32 respCode = 2;</code>
     */
    java.util.List<java.lang.Integer> getRespCodeList();
    /**
     * <code>repeated int32 respCode = 2;</code>
     */
    int getRespCodeCount();
    /**
     * <code>repeated int32 respCode = 2;</code>
     */
    int getRespCode(int index);

    /**
     * <code>repeated string desc = 3;</code>
     */
    java.util.List<java.lang.String>
        getDescList();
    /**
     * <code>repeated string desc = 3;</code>
     */
    int getDescCount();
    /**
     * <code>repeated string desc = 3;</code>
     */
    java.lang.String getDesc(int index);
    /**
     * <code>repeated string desc = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes(int index);
  }
  /**
   * Protobuf type {@code netty.SubscribeResp}
   */
  public  static final class SubscribeResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.SubscribeResp)
      SubscribeRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscribeResp.newBuilder() to construct.
    private SubscribeResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeResp() {
      subReqID_ = java.util.Collections.emptyList();
      respCode_ = java.util.Collections.emptyList();
      desc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubscribeResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                subReqID_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              subReqID_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                subReqID_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                subReqID_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                respCode_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              respCode_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                respCode_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                respCode_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                desc_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              desc_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          subReqID_ = java.util.Collections.unmodifiableList(subReqID_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          respCode_ = java.util.Collections.unmodifiableList(respCode_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          desc_ = desc_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp.class, io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp.Builder.class);
    }

    public static final int SUBREQID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> subReqID_;
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getSubReqIDList() {
      return subReqID_;
    }
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    public int getSubReqIDCount() {
      return subReqID_.size();
    }
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    public int getSubReqID(int index) {
      return subReqID_.get(index);
    }
    private int subReqIDMemoizedSerializedSize = -1;

    public static final int RESPCODE_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> respCode_;
    /**
     * <code>repeated int32 respCode = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getRespCodeList() {
      return respCode_;
    }
    /**
     * <code>repeated int32 respCode = 2;</code>
     */
    public int getRespCodeCount() {
      return respCode_.size();
    }
    /**
     * <code>repeated int32 respCode = 2;</code>
     */
    public int getRespCode(int index) {
      return respCode_.get(index);
    }
    private int respCodeMemoizedSerializedSize = -1;

    public static final int DESC_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList desc_;
    /**
     * <code>repeated string desc = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDescList() {
      return desc_;
    }
    /**
     * <code>repeated string desc = 3;</code>
     */
    public int getDescCount() {
      return desc_.size();
    }
    /**
     * <code>repeated string desc = 3;</code>
     */
    public java.lang.String getDesc(int index) {
      return desc_.get(index);
    }
    /**
     * <code>repeated string desc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes(int index) {
      return desc_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getSubReqIDList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(subReqIDMemoizedSerializedSize);
      }
      for (int i = 0; i < subReqID_.size(); i++) {
        output.writeInt32NoTag(subReqID_.get(i));
      }
      if (getRespCodeList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(respCodeMemoizedSerializedSize);
      }
      for (int i = 0; i < respCode_.size(); i++) {
        output.writeInt32NoTag(respCode_.get(i));
      }
      for (int i = 0; i < desc_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, desc_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < subReqID_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(subReqID_.get(i));
        }
        size += dataSize;
        if (!getSubReqIDList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        subReqIDMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < respCode_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(respCode_.get(i));
        }
        size += dataSize;
        if (!getRespCodeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        respCodeMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < desc_.size(); i++) {
          dataSize += computeStringSizeNoTag(desc_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDescList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp)) {
        return super.equals(obj);
      }
      io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp other = (io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp) obj;

      boolean result = true;
      result = result && getSubReqIDList()
          .equals(other.getSubReqIDList());
      result = result && getRespCodeList()
          .equals(other.getRespCodeList());
      result = result && getDescList()
          .equals(other.getDescList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSubReqIDCount() > 0) {
        hash = (37 * hash) + SUBREQID_FIELD_NUMBER;
        hash = (53 * hash) + getSubReqIDList().hashCode();
      }
      if (getRespCodeCount() > 0) {
        hash = (37 * hash) + RESPCODE_FIELD_NUMBER;
        hash = (53 * hash) + getRespCodeList().hashCode();
      }
      if (getDescCount() > 0) {
        hash = (37 * hash) + DESC_FIELD_NUMBER;
        hash = (53 * hash) + getDescList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.SubscribeResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.SubscribeResp)
        io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp.class, io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp.Builder.class);
      }

      // Construct using io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        subReqID_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        respCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
      }

      @java.lang.Override
      public io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp getDefaultInstanceForType() {
        return io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp.getDefaultInstance();
      }

      @java.lang.Override
      public io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp build() {
        io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp buildPartial() {
        io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp result = new io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          subReqID_ = java.util.Collections.unmodifiableList(subReqID_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.subReqID_ = subReqID_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          respCode_ = java.util.Collections.unmodifiableList(respCode_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.respCode_ = respCode_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          desc_ = desc_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.desc_ = desc_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp) {
          return mergeFrom((io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp other) {
        if (other == io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp.getDefaultInstance()) return this;
        if (!other.subReqID_.isEmpty()) {
          if (subReqID_.isEmpty()) {
            subReqID_ = other.subReqID_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSubReqIDIsMutable();
            subReqID_.addAll(other.subReqID_);
          }
          onChanged();
        }
        if (!other.respCode_.isEmpty()) {
          if (respCode_.isEmpty()) {
            respCode_ = other.respCode_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRespCodeIsMutable();
            respCode_.addAll(other.respCode_);
          }
          onChanged();
        }
        if (!other.desc_.isEmpty()) {
          if (desc_.isEmpty()) {
            desc_ = other.desc_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDescIsMutable();
            desc_.addAll(other.desc_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> subReqID_ = java.util.Collections.emptyList();
      private void ensureSubReqIDIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          subReqID_ = new java.util.ArrayList<java.lang.Integer>(subReqID_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getSubReqIDList() {
        return java.util.Collections.unmodifiableList(subReqID_);
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public int getSubReqIDCount() {
        return subReqID_.size();
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public int getSubReqID(int index) {
        return subReqID_.get(index);
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public Builder setSubReqID(
          int index, int value) {
        ensureSubReqIDIsMutable();
        subReqID_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public Builder addSubReqID(int value) {
        ensureSubReqIDIsMutable();
        subReqID_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public Builder addAllSubReqID(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSubReqIDIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subReqID_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public Builder clearSubReqID() {
        subReqID_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> respCode_ = java.util.Collections.emptyList();
      private void ensureRespCodeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          respCode_ = new java.util.ArrayList<java.lang.Integer>(respCode_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 respCode = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getRespCodeList() {
        return java.util.Collections.unmodifiableList(respCode_);
      }
      /**
       * <code>repeated int32 respCode = 2;</code>
       */
      public int getRespCodeCount() {
        return respCode_.size();
      }
      /**
       * <code>repeated int32 respCode = 2;</code>
       */
      public int getRespCode(int index) {
        return respCode_.get(index);
      }
      /**
       * <code>repeated int32 respCode = 2;</code>
       */
      public Builder setRespCode(
          int index, int value) {
        ensureRespCodeIsMutable();
        respCode_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 respCode = 2;</code>
       */
      public Builder addRespCode(int value) {
        ensureRespCodeIsMutable();
        respCode_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 respCode = 2;</code>
       */
      public Builder addAllRespCode(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRespCodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, respCode_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 respCode = 2;</code>
       */
      public Builder clearRespCode() {
        respCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList desc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDescIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          desc_ = new com.google.protobuf.LazyStringArrayList(desc_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDescList() {
        return desc_.getUnmodifiableView();
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public int getDescCount() {
        return desc_.size();
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public java.lang.String getDesc(int index) {
        return desc_.get(index);
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes(int index) {
        return desc_.getByteString(index);
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public Builder setDesc(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDescIsMutable();
        desc_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public Builder addDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDescIsMutable();
        desc_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public Builder addAllDesc(
          java.lang.Iterable<java.lang.String> values) {
        ensureDescIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, desc_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public Builder clearDesc() {
        desc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string desc = 3;</code>
       */
      public Builder addDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDescIsMutable();
        desc_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.SubscribeResp)
    }

    // @@protoc_insertion_point(class_scope:netty.SubscribeResp)
    private static final io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp();
    }

    public static io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeResp>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeResp>() {
      @java.lang.Override
      public SubscribeResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubscribeResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubscribeResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscribeResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.netty.nettyBook2Example.chapter8_Protobuf.SubscribeRespProto.SubscribeResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_SubscribeResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_SubscribeResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SubscribeResp.proto\022\005netty\"A\n\rSubscrib" +
      "eResp\022\020\n\010subReqID\030\001 \003(\005\022\020\n\010respCode\030\002 \003(" +
      "\005\022\014\n\004desc\030\003 \003(\tBB\n,io.netty.nettyBook2Ex" +
      "ample.chapter8_ProtobufB\022SubscribeRespPr" +
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_SubscribeResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_SubscribeResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_SubscribeResp_descriptor,
        new java.lang.String[] { "SubReqID", "RespCode", "Desc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
